const constants = {
    SET_PLAYER_NAME:"SET_PLAYER_NAME",
    SET_LEVEL:"SET_LEVEL",
    SET_CATEGORIES:"SET_CATEGORIES",
    SET_SELECTED_CATEGORY:"SET_SELECTED_CATEGORY",
    SET_CURRENT_CATEGORY_QUESTIONS:"SET_CURRENT_CATEGORY_QUESTIONS",
    SET_QUESTION_NO:"SET_QUESTION_NO",
    SET_TIMER:"SET_TIMER",
    INCREMENT_CORRECT_QUESTION_NO:"INCREMENT_CORRECT_QUESTION_NO",
    INCREMENT_WRONG_QUESTION_NO:"INCREMENT_WRONG_QUESTION_NO",
    INCREMENT_SKIP_QUESTION_NO:"INCREMENT_SKIP_QUESTION_NO",
    RESET_SELECTED_CATEGORY:"RESET_SELECTED_CATEGORY",
    RESET_CORRECT_ANSWER:"RESET_CORRECT_ANSWER",
    RESET_WRONG_ANSWER:"RESET_WRONG_ANSWER",
    RESET_SKIP_ANSWER:"RESET_SKIP_ANSWER"
}
export default constants;